### ISSUE TITLE
Fabric 1.20.1 port

### ISSUE THREAD

**Issue by Letus252** [RicoBrase/ChatCalculator#5]
Hey, I love your mod, very useful when I have to do quick math. Can you port it to minecraft 1.20.1 fabric? I recently got a bit into new minecraft and fabric is so much better for performance than forge. (Also maybe add Modrinth site so more people can find your mod?).

**Comment by RicoBrase** [comment]
@Letus252 I've ported ChatCalculator mod to fabric - at the moment, I plan to keep both Forge (maybe NeoForge in the future?) and Fabric versions.
You can download it from https://github.com/RicoBrase/ChatCalculator/releases/tag/1.6.0-fabric0.92.0%2B1.20.1 or the CurseForge project page.

Thank you for submitting your idea.

And thank you aswell for mentioning Modrinth, I had never heard of that previously.
I have created a project page, which is currently under review by their moderators.
As soon as it is successfully reviewed and published, I will add a link to the README.

**Comment by RicoBrase** [comment]
Modrinth page is now listed.

https://modrinth.com/mod/chatcalculator
